-   name:   preconfigre
    hosts: localhost
    tasks:
    - copy:
        src: "../master.gitconfig" 
        dest: "~/.gitconfig"
    - homebrew:
         name: "bat"
         state: "latest"
             