/**
 * Ride Share API
 * API provide capability to cancel fulfillment of all kind of documents(Revenue Tickets,Award Ticekts, Efee, EMD) and refund to original  form of payments like Credit card, Check, RealEx, UATP etc.This API can also handle \"No documents\" scenarios for BARTS. Document refund eligibility criteria is analysed by Rules engine based. Customer will be notified by email(predefined email template)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ETProd.DeltaTechnology@delta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MoreInfo {
    /**
     * Each exact property field that was validated
     */
    field: string;
    /**
     * Each error message on the property level validation done by the API
     */
    message: string;
}
